import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../collections/domain/entities/collection.dart';
import '../../../collections/domain/entities/collection_section.dart';
import '../../../collections/presentation/providers/collection_section_provider.dart';
import '../../../fields/presentation/providers/field_provider.dart';
import '../../data/item_state_store.dart';
import '../../domain/entities/item.dart';
import '../providers/item_provider.dart';
import 'item_detail_page.dart';

class ItemsPage extends ConsumerStatefulWidget { final Collection collection; final String? sectionId; final String? sectionName; const ItemsPage({super.key,required this.collection,this.sectionId,this.sectionName}); @override ConsumerState<ItemsPage> createState()=>_ItemsPageState(); }
class _ItemsPageState extends ConsumerState<ItemsPage>{ String search=''; String? sortField; bool descending=false; CollectionItemStatus? statusFilter; final Map<String,String> valueFilters={};
  List<CollectionSection> _children(List<CollectionSection> sections)=>sections.where((s)=>s.parentId==widget.sectionId).toList()..sort((a,b)=>a.sortOrder.compareTo(b.sortOrder));
  String _value(Item item,Map<String,Map<String,String>> values,String id)=>values[item.id]?[id]??'';
  List<dynamic> _filterFields(List<dynamic> fields,Map<String,Map<String,String>> values,List<Item> items)=>fields.where((f){final d=items.map((i)=>_value(i,values,f.id)).where((v)=>v.isNotEmpty).toSet();return f.id.toString().isNotEmpty&&f.label.toString().isNotEmpty&&d.length>1;}).toList();
  List<Item> _prepare(List<Item> source,Map<String,Map<String,String>> values,Map<String,ItemState> states){final q=search.trim().toLowerCase();final result=source.where((item){final s=states[item.id]??ItemState(updatedAt:DateTime.now());if(statusFilter!=null&&s.status!=statusFilter)return false;for(final f in valueFilters.entries){if(_value(item,values,f.key)!=f.value)return false;}if(q.isEmpty)return true;return '${item.id} ${(values[item.id]?.values??const <String>[]).join(' ')}'.toLowerCase().contains(q);}).toList();result.sort((a,b){if(sortField==null)return a.sortOrder.compareTo(b.sortOrder);final av=_value(a,values,sortField!);final bv=_value(b,values,sortField!);final an=double.tryParse(av.replaceAll(',','.'));final bn=double.tryParse(bv.replaceAll(',','.'));final c=an!=null&&bn!=null?an.compareTo(bn):av.toLowerCase().compareTo(bv.toLowerCase());return descending?-c:c;});return result;}
  void _refresh(){ref.invalidate(itemsProvider(widget.collection.id));ref.invalidate(collectionItemValuesProvider(widget.collection.id));ref.invalidate(collectionSectionsProvider(widget.collection.id));setState((){});}
  @override Widget build(BuildContext context){final sections=ref.watch(collectionSectionsProvider(widget.collection.id));return sections.when(loading:()=>_shell(context,widget.sectionName??widget.collection.name,const Center(child:CircularProgressIndicator())),error:(e,_)=>_shell(context,widget.sectionName??widget.collection.name,Center(child:Text('Ошибка разделов: $e'))),data:(all){final children=_children(all);if(children.isNotEmpty||(widget.sectionId==null&&all.isNotEmpty))return _browser(context,all);return _items(context);});}
  Widget _shell(BuildContext c,String title,Widget body)=>Scaffold(appBar:AppBar(title:Text(title)),body:body);
  Widget _browser(BuildContext c,List<CollectionSection> all){final children=widget.sectionId==null?all.where((s)=>s.parentId==null).toList():_children(all);return _shell(c,widget.sectionName??widget.collection.name,ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const Icon(Icons.account_tree_outlined),title:Text(widget.sectionId==null?'Полный каталог':widget.sectionName??'Раздел'),subtitle:const Text('Фильтры появляются только на уровне предметов.'))),const SizedBox(height:12),...children.map((s)=>Card(margin:const EdgeInsets.only(bottom:10),child:ListTile(leading:const CircleAvatar(child:Icon(Icons.folder_outlined)),title:Text(s.name),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ItemsPage(collection:widget.collection,sectionId:s.id,sectionName:s.name)))))]));}
  Widget _items(BuildContext c){final items=ref.watch(itemsProvider(widget.collection.id));final fields=ref.watch(fieldsProvider(widget.collection.id));final values=ref.watch(collectionItemValuesProvider(widget.collection.id));return _shell(c,widget.sectionName==null?widget.collection.name:'${widget.collection.name} · ${widget.sectionName}',items.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text('Ошибка: $e')),data:(list)=>values.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text('Ошибка значений: $e')),data:(map)=>fields.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text('Ошибка полей: $e')),data:(fs){final sectionItems=list.where((i)=>i.sectionId==widget.sectionId).toList();final filterFields=_filterFields(fs,map,sectionItems);return FutureBuilder<Map<String,ItemState>>(future:ItemStateStore.loadAll(),builder:(context,snapshot){final states=snapshot.data??{};final prepared=_prepare(sectionItems,map,states);final active=sortField!=null||descending||statusFilter!=null||valueFilters.isNotEmpty;return RefreshIndicator(onRefresh:()async=>_refresh(),child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.all(12),children:[TextField(decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'Поиск по предметам',suffixIcon:search.isEmpty?null:IconButton(onPressed:()=>setState(()=>search=''),icon:const Icon(Icons.clear)),border:const OutlineInputBorder()),onChanged:(v)=>setState(()=>search=v)),const SizedBox(height:8),Align(alignment:Alignment.centerRight,child:FilledButton.tonalIcon(onPressed:()=>_filters(context,fs,filterFields,map,sectionItems),icon:const Icon(Icons.tune),label:Text(active?'Фильтры активны':'Фильтры и сортировка'))),if(active)Wrap(spacing:6,runSpacing:6,children:[if(sortField!=null)Chip(label:Text('Сортировка: ${_label(fs,sortField!)}')),if(statusFilter!=null)Chip(label:Text(statusFilter!.title)),...valueFilters.entries.map((e)=>Chip(label:Text('${_label(fs,e.key)}: ${e.value}')))]),if(prepared.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(24),child:Text('Предметы не найдены',textAlign:TextAlign.center))) else ...prepared.asMap().entries.map((e)=>_Card(item:e.value,index:e.key,values:map,fields:fs,state:states[e.value.id]??ItemState(updatedAt:DateTime.now()),onOpen:()async{await Navigator.push(c,MaterialPageRoute(builder:(_)=>ItemDetailPage(itemId:e.value.id)));_refresh();}))]));});})));}
  String _label(List<dynamic> fs,String id)=>fs.where((f)=>f.id==id).map((f)=>f.label.toString()).firstOrNull??id;
  Future<void> _filters(BuildContext c,List<dynamic> fs,List<dynamic> filterFields,Map<String,Map<String,String>> values,List<Item> items)async{await showModalBottomSheet<void>(context:c,isScrollControlled:true,builder:(sheet)=>StatefulBuilder(builder:(context,setSheet)=>SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Фильтры',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:12),DropdownButtonFormField<CollectionItemStatus?>(initialValue:statusFilter,decoration:const InputDecoration(labelText:'Наличие',border:OutlineInputBorder()),items:[const DropdownMenuItem<CollectionItemStatus?>(value:null,child:Text('Все')), ...CollectionItemStatus.values.map((s)=>DropdownMenuItem(value:s,child:Text(s.title)))],onChanged:(v){setSheet((){});setState(()=>statusFilter=v);}),const SizedBox(height:12),DropdownButtonFormField<String?>(initialValue:sortField,decoration:const InputDecoration(labelText:'Сортировка',border:OutlineInputBorder()),items:[const DropdownMenuItem<String?>(value:null,child:Text('По порядку каталога')), ...filterFields.map((f)=>DropdownMenuItem(value:f.id.toString(),child:Text('По ${f.label}')))],onChanged:(v){setSheet((){});setState(()=>sortField=v);}),SwitchListTile(title:Text(descending?'Обратная сортировка':'Прямая сортировка'),value:descending,onChanged:(v){setSheet((){});setState(()=>descending=v);}),...filterFields.map((f){final d=items.map((i)=>_value(i,values,f.id)).where((v)=>v.isNotEmpty).toSet().toList()..sort();return DropdownButtonFormField<String?>(initialValue:valueFilters[f.id],decoration:InputDecoration(labelText:f.label,border:const OutlineInputBorder()),items:[const DropdownMenuItem<String?>(value:null,child:Text('Все')), ...d.map((v)=>DropdownMenuItem(value:v,child:Text(v,overflow:TextOverflow.ellipsis)))],onChanged:(v){setSheet((){});setState(()=>v==null?valueFilters.remove(f.id):valueFilters[f.id]=v);});}),const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton(onPressed:(){setState((){sortField=null;descending=false;statusFilter=null;valueFilters.clear();});Navigator.pop(sheet);},child:const Text('Сбросить'))),const SizedBox(width:8),Expanded(child:FilledButton(onPressed:()=>Navigator.pop(sheet),child:const Text('Применить')))])]))));}
}
class _Card extends StatelessWidget{final Item item;final int index;final Map<String,Map<String,String>> values;final List<dynamic> fields;final ItemState state;final VoidCallback onOpen;const _Card({required this.item,required this.index,required this.values,required this.fields,required this.state,required this.onOpen});@override Widget build(BuildContext c){final iv=values[item.id]??{};final visible=fields.where((f)=>(iv[f.id]??'').isNotEmpty).take(3).toList();return Card(child:ListTile(leading:CircleAvatar(child:Text('${index+1}')),title:Text(visible.isEmpty?item.id:iv[visible.first.id]!,maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text('${state.status.title}${state.quantity>0?' · ${state.quantity} шт.':''}${visible.length>1?' · ${visible.skip(1).map((f)=>'${f.label}: ${iv[f.id]}').join(' · ')':''}',maxLines:2,overflow:TextOverflow.ellipsis),trailing:Icon(state.status==CollectionItemStatus.owned||state.status==CollectionItemStatus.storage?Icons.check_circle:state.status==CollectionItemStatus.wanted?Icons.shopping_cart_outlined:state.status==CollectionItemStatus.ordered?Icons.local_shipping_outlined:Icons.chevron_right),onTap:onOpen));}}
extension _FirstOrNull<T> on Iterable<T>{T? get firstOrNull=>isEmpty?null:first;}
