import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../catalogs/data/favorites_store.dart';
import '../../../fields/presentation/providers/field_provider.dart';
import '../../data/item_state_store.dart';
import '../../domain/entities/item_value.dart';
import '../../domain/entities/item_attachment.dart';
import '../providers/item_attachment_provider.dart';
import '../providers/item_provider.dart';

class ItemDetailPage extends ConsumerStatefulWidget { final String itemId; const ItemDetailPage({super.key,required this.itemId}); @override ConsumerState<ItemDetailPage> createState()=>_ItemDetailPageState(); }
class _ItemDetailPageState extends ConsumerState<ItemDetailPage>{ ItemState _state=ItemState(updatedAt:DateTime.now()); bool _favorite=false; bool _saving=false; @override void initState(){super.initState();_load();} Future<void> _load()async{final s=await ItemStateStore.load(widget.itemId);final f=await FavoritesStore.containsKey(FavoritesStore.itemKey(widget.itemId));if(mounted)setState((){_state=s;_favorite=f;});} Future<void> _save(dynamic item,ItemState state)async{setState(()=>_saving=true);try{final next=state.copyWith(updatedAt:DateTime.now());await ItemStateStore.save(widget.itemId,next,title:item.id);if(mounted)setState((){_state=next;_saving=false;});}catch(error){if(mounted){setState(()=>_saving=false);ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Ошибка сохранения: $error')));}}} Future<void> _favoriteToggle()async{final ids=await FavoritesStore.toggleKey(FavoritesStore.itemKey(widget.itemId));if(mounted)setState(()=>_favorite=ids.contains(FavoritesStore.itemKey(widget.itemId)));}
@override Widget build(BuildContext context){final itemAsync=ref.watch(itemProvider(widget.itemId));return Scaffold(appBar:AppBar(title:const Text('Предмет'),actions:[IconButton(onPressed:_favoriteToggle,icon:Icon(_favorite?Icons.star_rounded:Icons.star_border_rounded))]),body:itemAsync.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text(e.toString())),data:(item){if(item==null)return const Center(child:Text('Предмет не найден'));final values=ref.watch(itemValuesProvider(item.id));final attachments=ref.watch(itemAttachmentsProvider(item.id));final fields=ref.watch(fieldsProvider(item.collectionId));return fields.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text(e.toString())),data:(fs){final labels={for(final f in fs)f.id:f.label};return ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const Icon(Icons.inventory_2_outlined),title:Text(item.id),subtitle:Text('Каталог: ${item.collectionId}\nРаздел: ${item.sectionId??'Нет'}'))),const SizedBox(height:12),_StateCard(state:_state,saving:_saving,onChanged:(s)=>_save(item,s)),const SizedBox(height:12),_SectionCard(title:'Поля каталога (только чтение)',child:values.when(loading:()=>const CircularProgressIndicator(),error:(e,_)=>Text(e.toString()),data:(items)=>items.isEmpty?const Text('Нет заполненных полей'):Column(children:items.map((v)=>_ValueTile(value:v,label:labels[v.fieldId]??v.fieldId)).toList()))),const SizedBox(height:12),_SectionCard(title:'Вложения',child:attachments.when(loading:()=>const CircularProgressIndicator(),error:(e,_)=>Text(e.toString()),data:(items)=>items.isEmpty?const Text('Вложений нет'):Column(children:items.map((a)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.insert_drive_file_outlined),title:Text(a.path),subtitle:Text(a.type))).toList())))];});});});}
}
class _StateCard extends StatelessWidget{final ItemState state;final bool saving;final ValueChanged<ItemState> onChanged;const _StateCard({required this.state,required this.saving,required this.onChanged});Future<void> _note(BuildContext c)async{final controller=TextEditingController(text:state.note);final value=await showDialog<String>(context:c,builder:(d)=>AlertDialog(title:const Text('Личная заметка'),content:TextField(controller:controller,maxLines:5,decoration:const InputDecoration(border:OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Отмена')),FilledButton(onPressed:()=>Navigator.pop(d,controller.text.trim()),child:const Text('Сохранить'))]));controller.dispose();if(value!=null)onChanged(state.copyWith(note:value));}
@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Expanded(child:Text('Моё состояние',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800))),if(saving)const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2))]),const SizedBox(height:12),DropdownButtonFormField<CollectionItemStatus>(initialValue:state.status,decoration:const InputDecoration(labelText:'Статус',border:OutlineInputBorder()),items:CollectionItemStatus.values.map((s)=>DropdownMenuItem(value:s,child:Text(s.title))).toList(),onChanged:(v){if(v!=null)onChanged(state.copyWith(status:v,quantity:v==CollectionItemStatus.missing?0:(state.quantity==0?1:state.quantity)));}),const SizedBox(height:12),Row(children:[Expanded(child:TextFormField(initialValue:'${state.quantity}',keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Количество',border:OutlineInputBorder()),onFieldSubmitted:(v)=>onChanged(state.copyWith(quantity:int.tryParse(v)??state.quantity)))),const SizedBox(width:10),Expanded(child:TextFormField(initialValue:state.condition,decoration:const InputDecoration(labelText:'Состояние',border:OutlineInputBorder()),onFieldSubmitted:(v)=>onChanged(state.copyWith(condition:v))))]),const SizedBox(height:12),Row(children:[Expanded(child:Text(state.purchaseDate==null?'Дата покупки не указана':'Куплено: ${state.purchaseDate!.toLocal().toString().split(' ').first}')),TextButton.icon(onPressed:()async{final d=await showDatePicker(context:c,firstDate:DateTime(1900),lastDate:DateTime.now(),initialDate:state.purchaseDate??DateTime.now());if(d!=null)onChanged(state.copyWith(purchaseDate:d));},icon:const Icon(Icons.calendar_today_outlined),label:const Text('Дата'))]),TextFormField(initialValue:state.purchasePrice?.toString()??'',keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Цена покупки',prefixText:'€ ',border:OutlineInputBorder()),onFieldSubmitted:(v)=>onChanged(state.copyWith(purchasePrice:double.tryParse(v.replaceAll(',','.'))))),ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.note_alt_outlined),title:Text(state.note.isEmpty?'Добавить заметку':state.note,maxLines:3,overflow:TextOverflow.ellipsis),onTap:()=>_note(c))])));}
class _SectionCard extends StatelessWidget{final String title;final Widget child;const _SectionCard({required this.title,required this.child});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.titleMedium),const SizedBox(height:10),child])));}
class _ValueTile extends StatelessWidget{final ItemValue value;final String label;const _ValueTile({required this.value,required this.label});@override Widget build(BuildContext c)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(label),subtitle:Text(value.value));}
