import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/localization/app_localizations.dart';
import '../data/catalog_registry.dart';
import '../data/favorites_store.dart';
import 'catalog_online_page.dart';
import '../../collections/presentation/providers/collection_provider.dart';
import '../../collections/presentation/providers/collection_section_provider.dart';
import '../../items/presentation/providers/item_service_provider.dart';
import '../../items/presentation/pages/item_detail_page.dart';

class FavoritesPage extends ConsumerStatefulWidget { const FavoritesPage({super.key}); @override ConsumerState<FavoritesPage> createState()=>_FavoritesPageState(); }
class _FavoritesPageState extends ConsumerState<FavoritesPage>{ Set<String> ids={}; final Map<String,String> labels={}; VoidCallback? listener; @override void initState(){super.initState();listener=_load;FavoritesStore.revision.addListener(listener!);_load();} @override void dispose(){if(listener!=null)FavoritesStore.revision.removeListener(listener!);super.dispose();} Future<void> _load()async{final favorites=await FavoritesStore.loadKeys();final collections=ref.read(collectionsProvider).valueOrNull??const[];final service=ref.read(itemServiceProvider);final map=<String,String>{};final sectionService=await ref.read(collectionSectionServiceProvider.future);for(final c in collections){for(final s in await sectionService.getSections(c.id)){map[FavoritesStore.sectionKey(s.id)]='${c.name} · ${s.name}';}for(final i in await service.getItems(c.id)){map[FavoritesStore.itemKey(i.id)]='${c.name} · ${i.id}';}}if(mounted)setState((){ids=favorites;labels..clear()..addAll(map);});}
@override Widget build(BuildContext context){final l10n=AppLocalizations.of(context);final catalogs=CatalogRegistry.all.where((c)=>ids.contains(FavoritesStore.catalogKey(c.id))).toList();final sections=ids.where((x)=>x.startsWith('section:')).toList();final items=ids.where((x)=>x.startsWith('item:')).toList();if(ids.isEmpty)return Scaffold(appBar:AppBar(title:Text(l10n.favorites)),body:Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.star_border_rounded,size:64,color:Theme.of(context).colorScheme.primary),const SizedBox(height:16),Text(l10n.noFavorites,textAlign:TextAlign.center,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:8),Text(l10n.noFavoritesDescription,textAlign:TextAlign.center)]))));return Scaffold(appBar:AppBar(title:Text(l10n.favorites),actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh))]),body:ListView(padding:const EdgeInsets.all(16),children:[if(catalogs.isNotEmpty)const _Heading('Коллекции',Icons.collections_bookmark_outlined),...catalogs.map((c)=>_Tile(l10n.catalogName(c.id),'Каталог · v${c.version}',Icons.inventory_2_outlined,()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>CatalogOnlinePage(catalog:c))),()=>FavoritesStore.remove(c.id))),if(sections.isNotEmpty)const _Heading('Разделы',Icons.folder_outlined),...sections.map((id)=>_Tile(labels[id]??id.substring(8),'Раздел каталога',Icons.folder_outlined,(){},()=>FavoritesStore.removeKey(id))),if(items.isNotEmpty)const _Heading('Предметы',Icons.inventory_2_outlined),...items.map((id)=>_Tile(labels[id]??id.substring(5),'Предмет коллекции',Icons.inventory_2_outlined,()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ItemDetailPage(itemId:id.substring(5)))),()=>FavoritesStore.removeKey(id)))]));}
}
class _Heading extends StatelessWidget{final String title;final IconData icon;const _Heading(this.title,this.icon);@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(top:12,bottom:8),child:Row(children:[Icon(icon),const SizedBox(width:8),Text(title,style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800))]));}
class _Tile extends StatelessWidget{final String title,subtitle;final IconData icon;final VoidCallback onTap,onRemove;const _Tile(this.title,this.subtitle,this.icon,this.onTap,this.onRemove);@override Widget build(BuildContext c)=>Card(child:ListTile(leading:CircleAvatar(child:Icon(icon)),title:Text(title),subtitle:Text(subtitle),onTap:onTap,trailing:IconButton(onPressed:onRemove,icon:const Icon(Icons.star_rounded))));}
