import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../data/catalog_registry.dart';
import '../domain/entities/catalog_definition.dart';
import '../domain/entities/catalog_entry_definition.dart';
import '../../collections/domain/entities/collection.dart';
import '../../collections/presentation/providers/collection_provider.dart';
import '../../items/domain/entities/item.dart';
import '../../items/presentation/pages/item_detail_page.dart';
import '../../items/presentation/providers/item_service_provider.dart';
import 'catalog_online_page.dart';

class GlobalSearchPage extends ConsumerStatefulWidget { const GlobalSearchPage({super.key}); @override ConsumerState<GlobalSearchPage> createState() => _GlobalSearchPageState(); }
class _GlobalSearchPageState extends ConsumerState<GlobalSearchPage> {
  final _controller = TextEditingController(); String _query = ''; bool _loading = false; List<_SearchResult> _results = const [];
  @override void initState() { super.initState(); _controller.addListener(() => setState(() => _query = _controller.text)); }
  @override void dispose() { _controller.dispose(); super.dispose(); }
  String _normalize(String value) { var text = value.toLowerCase().trim(); const map = {'q':'й','w':'ц','e':'у','r':'к','t':'е','y':'н','u':'г','i':'ш','o':'щ','p':'з','a':'ф','s':'ы','d':'в','f':'а','g':'п','h':'р','j':'о','k':'л','l':'д','z':'я','x':'ч','c':'с','v':'м','b':'и','n':'т','m':'ь'}; if (text.codeUnits.every((unit) => unit < 128)) text = text.split('').map((char) => map[char] ?? char).join(); return text.replaceAll(RegExp(r'[^\p{L}\p{N}]+', unicode: true), ' '); }
  int _distance(String a, String b) { final row = List<int>.generate(b.length + 1, (i) => i); for (var i = 0; i < a.length; i++) { var diagonal = row[0]; row[0] = i + 1; for (var j = 0; j < b.length; j++) { final old = row[j + 1]; final cost = a[i] == b[j] ? 0 : 1; row[j + 1] = [row[j + 1] + 1, row[j] + 1, diagonal + cost].reduce((x, y) => x < y ? x : y); diagonal = old; } } return row[b.length]; }
  double _score(String query, String text) { if (text.contains(query)) return 1; var best = 0.0; for (final token in text.split(' ').where((x) => x.isNotEmpty)) { final max = query.length > token.length ? query.length : token.length; if (max == 0) continue; final score = 1 - _distance(query, token) / max; if (score > best) best = score; } return best; }
  Future<void> _search() async { final query = _normalize(_query); if (query.isEmpty) { setState(() => _results = const []); return; } setState(() => _loading = true); final results = <_SearchResult>[]; for (final catalog in CatalogRegistry.all) { final score = _score(query, _normalize('${catalog.name} ${catalog.description}')); if (score >= .55) results.add(_SearchResult.catalog(catalog, score)); for (final entry in catalog.entries) { final entryScore = _score(query, _normalize('${entry.title} ${entry.primaryValue} ${entry.subtitle} ${entry.attributes.values.join(' ')}')); if (entryScore >= .55) results.add(_SearchResult.entry(catalog, entry.title, entry.subtitle, entryScore)); } } final collections = ref.read(collectionsProvider).valueOrNull ?? const <Collection>[]; final service = ref.read(itemServiceProvider); for (final collection in collections) { for (final item in await service.getItems(collection.id)) { final values = await service.getValues(item.id); final score = _score(query, _normalize('${collection.name} ${item.id} ${values.map((value) => value.value).join(' ')}')); if (score >= .55) results.add(_SearchResult.item(collection, item, score)); } } results.sort((a, b) => b.score.compareTo(a.score)); if (!mounted) return; setState(() { _results = results.take(100).toList(); _loading = false; }); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Глобальный поиск')), body: Column(children: [Padding(padding: const EdgeInsets.all(16), child: TextField(controller: _controller, autofocus: true, onSubmitted: (_) => _search(), decoration: InputDecoration(prefixIcon: const Icon(Icons.search), hintText: 'Предмет, серия, коллекция, заметка...', suffixIcon: _query.isEmpty ? null : IconButton(onPressed: _controller.clear, icon: const Icon(Icons.clear)), border: const OutlineInputBorder()))), Align(alignment: Alignment.centerRight, child: Padding(padding: const EdgeInsets.symmetric(horizontal: 16), child: FilledButton.icon(onPressed: _loading ? null : _search, icon: const Icon(Icons.search), label: const Text('Найти')))), const SizedBox(height: 8), Expanded(child: _loading ? const Center(child: CircularProgressIndicator()) : _query.isEmpty ? const Center(child: Text('Введите запрос')) : _results.isEmpty ? const Center(child: Text('Ничего не найдено')) : ListView.separated(padding: const EdgeInsets.all(16), itemCount: _results.length, separatorBuilder: (_, __) => const SizedBox(height: 8), itemBuilder: (context, index) { final result = _results[index]; return Card(child: ListTile(leading: Icon(result.icon), title: Text(result.title), subtitle: Text(result.subtitle), trailing: const Icon(Icons.chevron_right), onTap: () { if (result.catalog != null) Navigator.push(context, MaterialPageRoute(builder: (_) => CatalogOnlinePage(catalog: result.catalog!))); else if (result.item != null) Navigator.push(context, MaterialPageRoute(builder: (_) => ItemDetailPage(itemId: result.item!.id))); })); }))]));
}
class _SearchResult { final String title; final String subtitle; final double score; final IconData icon; final CatalogDefinition? catalog; final Item? item; const _SearchResult({required this.title, required this.subtitle, required this.score, required this.icon, this.catalog, this.item}); factory _SearchResult.catalog(CatalogDefinition c, double s) => _SearchResult(title: c.name, subtitle: 'Коллекция · версия ${c.version}', score: s, icon: Icons.collections_bookmark_outlined, catalog: c); factory _SearchResult.entry(CatalogDefinition c, String t, String st, double s) => _SearchResult(title: t, subtitle: '${c.name} · $st', score: s, icon: Icons.inventory_2_outlined, catalog: c); factory _SearchResult.item(Collection c, Item i, double s) => _SearchResult(title: i.id, subtitle: 'Моя коллекция · ${c.name}', score: s, icon: Icons.check_circle_outline, item: i); }
