import 'dart:convert';
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import '../../../catalogs/data/favorites_store.dart';
import '../../../items/data/item_state_store.dart';
import '../../data/collection_history_store.dart';

class BackupImportPage extends StatefulWidget { const BackupImportPage({super.key}); @override State<BackupImportPage> createState()=>_BackupImportPageState(); }
class _BackupImportPageState extends State<BackupImportPage>{ bool loading=false; String message='Выберите JSON-резервную копию. Структура централизованного каталога не импортируется.'; Future<void> importBackup()async{setState((){loading=true;message='Чтение резервной копии...';});try{const group=XTypeGroup(label:'JSON',extensions:['json'],mimeTypes:['application/json'],uniformTypeIdentifiers:['public.json']);final file=await openFile(acceptedTypeGroups:[group]);if(file==null){if(mounted)setState((){loading=false;message='Импорт отменён.';});return;}final decoded=jsonDecode(await file.readAsString());if(decoded is! Map)throw const FormatException('Некорректный JSON backup');final states=<String,ItemState>{};final rawStates=decoded['itemStates'];if(rawStates is Map){for(final e in rawStates.entries){if(e.value is Map)states[e.key.toString()]=ItemState.fromJson(Map<String,dynamic>.from(e.value as Map));}}await ItemStateStore.replaceAll(states);final rawFavorites=decoded['favorites'];if(rawFavorites is List)await FavoritesStore.replaceAll(rawFavorites.map((v)=>v.toString()).toSet());final rawHistory=decoded['history'];if(rawHistory is List)await CollectionHistoryStore.replaceAll(rawHistory.whereType<Map>().map((e)=>CollectionHistoryEntry.fromJson(Map<String,dynamic>.from(e))).toList());if(mounted)setState((){loading=false;message='Импорт завершён. Состояний восстановлено: ${states.length}. Каталог не изменялся.';});}catch(error){if(mounted)setState((){loading=false;message='Ошибка импорта: $error';});}}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Восстановление')),body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:560),child:Padding(padding:const EdgeInsets.all(24),child:Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.restore_outlined,size:56),const SizedBox(height:16),Text(message,textAlign:TextAlign.center),const SizedBox(height:20),FilledButton.icon(onPressed:loading?null:importBackup,icon:const Icon(Icons.file_open_outlined),label:const Text('Выбрать JSON'))])))))));}
