import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../fields/presentation/providers/field_provider.dart';
import '../../../items/presentation/pages/item_detail_page.dart';
import '../../../items/presentation/pages/items_page.dart';
import '../../../items/presentation/providers/item_provider.dart';
import '../../domain/entities/collection.dart';
import '../providers/collection_provider.dart';

class CollectionDetailPage extends ConsumerWidget { final String collectionId; final String collectionName; const CollectionDetailPage({super.key,required this.collectionId,required this.collectionName}); @override Widget build(BuildContext context,WidgetRef ref){final collection=ref.watch(collectionProvider(collectionId));final fields=ref.watch(fieldsProvider(collectionId));final items=ref.watch(itemsProvider(collectionId));return Scaffold(appBar:AppBar(title:Text(collectionName)),body:RefreshIndicator(onRefresh:()async{ref.invalidate(collectionProvider(collectionId));ref.invalidate(fieldsProvider(collectionId));ref.invalidate(itemsProvider(collectionId));},child:ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:const Icon(Icons.lock_outline),title:Text(collectionName),subtitle:Text('Централизованный каталог · пользователь меняет только личное состояние'))),const SizedBox(height:12),FilledButton.icon(onPressed:(){final c=collection.valueOrNull??Collection(id:collectionId,name:collectionName,createdAt:DateTime.now(),updatedAt:DateTime.now());Navigator.push(context,MaterialPageRoute(builder:(_)=>ItemsPage(collection:c)));},icon:const Icon(Icons.view_list),label:const Text('Открыть каталог')),const SizedBox(height:12),Card(child:ListTile(title:const Text('Статистика'),subtitle:items.when(data:(i)=>fields.when(data:(f)=>Text('Предметов: ${i.length} · Полей: ${f.length}'),loading:()=>Text('Предметов: ${i.length}'),error:(_,__)=>Text('Предметов: ${i.length}')),loading:()=>const Text('Загрузка...'),error:(e,_)=>Text(e.toString())),leading:const Icon(Icons.insights_outlined))),const SizedBox(height:12),Card(child:ExpansionTile(title:const Text('Предметы'),leading:const Icon(Icons.inventory_2_outlined),children:items.when(data:(list)=>list.take(10).map((item)=>ListTile(title:Text(item.id),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ItemDetailPage(itemId:item.id)))).toList(),loading:()=>[const Padding(padding:EdgeInsets.all(16),child:CircularProgressIndicator())],error:(e,_)=>[ListTile(title:Text(e.toString()))]))),Card(child:ExpansionTile(title:const Text('Поля каталога'),leading:const Icon(Icons.label_outline),children:fields.when(data:(list)=>list.map((field)=>ListTile(title:Text(field.label),subtitle:Text(field.type.name),trailing:const Icon(Icons.lock_outline))).toList(),loading:()=>[const Padding(padding:EdgeInsets.all(16),child:CircularProgressIndicator())],error:(e,_)=>[ListTile(title:Text(e.toString()))]))) ])));}}
